@startuml Sistema Bancário

title Sistema Bancário

class Usuário{
    -id: string
    -nome: string
    -dataDeNascimento: date
    -cpf: string
    -telefone: string
    --
    +construct(id, nome, dataDeNascimento, cpf, telefone)
    +getters()
    +setters()
}

class Cliente {
    -usuario: Usuário
    -contaBancaria: ContaBancaria
    --
    +getters()
    +setters()
}

class ContaBancaria{
    -id: string
    --
    +construct(id)
    +depositar(double valor)
    +sacar(double valor)
    +getters()
    +setters()
}

class ContaCorrente{
    -contaBancaria: ContaBancaria
    --
    +depositar(double valor)
}

class ContaPoupança{
    -contaBancaria: ContaBancaria
    +depositar()
}

class ContaSalário{
    -contaBancaria: ContaBancaria
}

class Agência{
    --
    +getters()
    +setters()
}

class Banco{
    --
    +getters()
    +setters()
}

Usuário "1..1" <|-- "1..1" Cliente
Cliente "1..*" *-up- "1..1" ContaBancaria
ContaBancaria <|-- ContaCorrente
ContaBancaria <|-- ContaPoupança
ContaBancaria <|-- ContaSalário
ContaBancaria "1..*" -up- "1..1" Agência
Agência "1..*" -up- "1..1" Banco

@enduml