@startuml biblioteca
title Biblioteca

entity Livro #white;line.bold;line:SteelBlue{
    *<color: SteelBlue>isbn: VARCHAR[20] <<PK>>
    genero: VARCHAR[255]
    paginas: INT
    sinopse: TEXT
    ano: DATE
    --
    <color: SlateBlue>id_Autor: int[10] <<FK>>
    id_Editora: int[10] <<FK>>
    id_Status: int[10] <<FK>>
}

entity Autor #white;line.bold;line:Slateblue{
    *<color: SlateBlue>id: int[10] <<PK>>
    nome: VARCHAR[255]
    dataDeNascimento: DATE
    --
    id_editora: int[10] <<FK>>
}

entity Editora{
    *id: int[10] <<PK>>
    nome: VARCHAR[255]
    
}

entity Cliente{
    *id_Cliente int <<PK>>
    isbn VARCHAR[20] <<FK>>
    nome VARCHAR[255]
    cpf VARCHAR[20]
}

entity Status{
    *id_Status int <<PK>>
    id_Cliente int <<FK>>
    id_Emprestimo <<FK>>
    Status CHAR[1]
}

entity Empréstimo{
    id_Emprestimo int <<PK>>
    dataDeRetirada DATE
    dataDeEntrega DATE    
}

Livro ||--|| Status
Livro }|-[#SlateBlue]-|{ Autor
Livro }|--o| Editora
Livro |o--o| Cliente
Autor }|--|{ Editora
Status ||--o| Empréstimo
@enduml