@startuml biblioteca
title Biblioteca

entity Livro #white;line.bold;line:SteelBlue{
    *<color: SteelBlue>isbn: VARCHAR[20] <<PK>>
    genero: VARCHAR[255]
    paginas: INT
    sinopse: TEXT
    sessao: VARCHAR[255]
    ano: DATE
    status: CHAR[1]
    --
    <color: SlateBlue>id_Autor: INT[10] <<FK>>
    <color: Red>id_Editora: INT[10] <<FK>>
    <color: Green>id_Emprestimo: INT[10] <<FK>>
}

entity Autor #white;line.bold;line:Slateblue{
    *<color: SlateBlue>id: int[10] <<PK>>
    nome: VARCHAR[255]
    dataDeNascimento: DATE


}

entity Editora #white;line.bold;line:Red{
    *<color: Red>id: INT[10] <<PK>>
    nome: VARCHAR[255]
    cnpj: VARCHAR[255]
    cep: VARCHAR[255]
    
}

entity Empréstimo #white;line.bold;line:Green{
    *<color: Green>id: int[10] <<PK>>
    dataDeRetirada: DATE
    vencimento: DATE  
    --
    <color: Orange>id_Cliente INT [10] <<FK>>
    <color: SteelBlue>isbn VARCHAR[20] <<FK>>
}

entity Cliente #white;line.bold;line:Orange{
    *<color: Orange>id_Cliente: INT[10] <<PK>>
    nome: VARCHAR[255]
    cpf: VARCHAR[20]
    --
    <color: Green>id_Emprestimo: INT [10] <<FK>>
}

Livro }|-[#SlateBlue]-|{ Autor
Livro }|-[#Red]-o| Editora
Livro ||-[#SteelBlue]-o| Empréstimo
Cliente ||-[#Orange]-o{ Empréstimo
@enduml