@startuml databola
title databola

entity Cidade{
id INT[10] <<PK>>
nome VARCHAR[100]
}

entity Cliente{
id INT[10] <<PK>>
nome VARCHAR[100]
dataDeNascimento DATE 
salario DOUBLE[10.6]
id_cidade int[10] <<FK>>
}

Cidade ||--o{ Cliente

@enduml